apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: tailscale
    namespace: argocd
spec:
    source:
        repoURL: https://github.com/CompositeCoding/homeLab.git
        targetRevision: HEAD
        path: apps/tailscale
    project: default
    destination:
        server: https://kubernetes.default.svc
        namespace: tailscale
    syncPolicy:
        automated:
            enabled: true
