apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: n8n-statefulset
spec:
    selector:
        matchLabels:
            app: n8n
    serviceName: n8n-service
    replicas: 1
    template:
        metadata:
            labels:
                app: n8n
        spec:
            containers:
                - name: n8n
                  image: n8nio/n8n:1.121.2
                  resources:
                      limits:
                          memory: 2Gi
                  ports:
                      - containerPort: 5678
                  env:
                      - name: GENERIC_TIMEZONE
                        value: "America/Toronto"
                      - name: TZ
                        value: "America/Toronto"
                      - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
                        value: "true"
                      - name: N8N_RUNNERS_ENABLED
                        value: "true"
                  volumeMounts:
                      - name: n8n-data
                        mountPath: /home/node/.n8n
    volumeClaimTemplates:
        - metadata:
              name: n8n-data
          spec:
              selector:
                  matchLabels:
                      app: n8n
              accessModes: ["ReadWriteOnce"]
              storageClassName: local-storage
              resources:
                  requests:
                      storage: 30Gi
