apiVersion: v1
kind: PersistentVolume
metadata:
    name: n8n-data
    labels:
        app: n8n
spec:
    capacity:
        storage: 50Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: local-storage
    local:
        path: /var/mnt/local-volume/n8n
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                            - talos-n4r-glu
