apiVersion: v1
kind: PersistentVolume
metadata:
    name: n8n-data
    labels:
        app: n8n
spec:
    capacity:
        storage: 30Gi
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
