apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: nginx-app
    namespace: argocd
spec:
    project: default
    source:
        repoURL: "https://github.com/CompositeCoding/homeLab.git"
        targetRevision: main
        path: overlays # Points to Kustomize directory
    destination:
        server: "https://kubernetes.default.svc"
        namespace: home
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
