apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: postgres
spec:
    instances: 0
    storage:
        pvcTemplate:
            accessModes:
                - ReadWriteOnce
            storageClassName: local-storage
            resources:
                requests:
                    storage: 50Gi
            selector:
                matchLabels:
                    app: postgres-data
    bootstrap:
        initdb:
            database: app
            owner: app
