apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-data-0
    labels:
        app: postgres-data
spec:
    capacity:
        storage: 30Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: local-storage
    local:
        path: /var/mnt/local-volume/postgres-data-0
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                            - talos-n4r-glu
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-data-1
    labels:
        app: postgres-data
spec:
    capacity:
        storage: 30Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: local-storage
    local:
        path: /var/mnt/local-volume/postgres-data-1
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                            - talos-n4r-glu
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-data-2
    labels:
        app: postgres-data
spec:
    capacity:
        storage: 30Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: local-storage
    local:
        path: /var/mnt/local-volume/postgres-data-2
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                            - talos-n4r-glu
